version: '3.5'

services:

  front:
    image: 'jusdino/minecraft-auto-start-front:latest'
    build:
      context: 'front'
      dockerfile: 'Dockerfile'
    volumes:
      - './front/container:/usr/src/app'
    ports:
      - '8080:5000'
    environment:
      APP_NAME: 'minecraft-auto-start'
      FLASK_DEBUG: '1'
      PYTHONUNBUFFERED: '0'
      APP_SETTINGS: 'front.config.ProductionConfig'
      DATABASE_URL: 'postgres://postgres:postgres@db:5432/users_dev'
      DATABASE_TEST_URL: 'postgres://postgres:postgres@db:5432/users_test'
    depends_on:
      - 'db'

  db:
    image: 'jusdino/minecraft-auto-start-db:latest'
    build:
      context: 'db'
      dockerfile: 'Dockerfile'
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'

  launcher:
    image: 'jusdino/minecraft-auto-start-launcher:latest'
    build:
      context: 'launcher'
      dockerfile: 'Dockerfile'
    environment:
      SSH_AGENT_KEY: ${SSH_AGENT_KEY}
      KNOWN_HOSTS: ${KNOWN_HOSTS}
      INFRA_LIVE_CLONE_URL: ${INFRA_LIVE_CLONE_URL}
      TARGET_SERVER_PATH: ${TARGET_SERVER_PATH}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
