version: '3.5'

services:

  launcher:
    image: launcher
    build:
      context: launcher
      dockerfile: Dockerfile
    volumes:
      - './launcher/container:/usr/src/app'
    ports:
      - 8080:5000
    environment:
      - APP_NAME=launcher
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=0
      - APP_SETTINGS=launcher.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/users_test
    depends_on:
      - db

  db:
    container_name: db
    build:
      context: db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
