version: '3.5'

services:

  launcher:
    image: 'jusdino/minecraft-auto-start-launcher:latest'
    build:
      context: 'launcher'
      dockerfile: 'Dockerfile'
    environment:
      SSH_AGENT_KEY: ${SSH_AGENT_KEY}
      KNOWN_HOSTS: ${KNOWN_HOSTS}
      INFRA_LIVE_CLONE_URL: ${INFRA_LIVE_CLONE_URL}
      TARGET_SERVER_PATH: ${TARGET_SERVER_PATH}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
